version: '3.1'

services:
  mysql:
    image: mariadb:10.4.18  # Updated to MariaDB 10.4.18
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/backups:/backups
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
      
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./volumes/poc-mini-fileserver:/var/www/poc-mini-fileserver
      - ./volumes/logs/log.txt:/var/www/logs/log.txt
      - ./volumes/legacy-edispo:/var/www/legacy-edispo
      - ./.env.fileserver:/var/www/poc-mini-fileserver/.env
      - ./volumes/uploads/poc-mini-fileserver:/var/www/uploads

    networks:
      - app-network
  
  nextjs:
    build:
      context: ./volumes/eoffice
      dockerfile: prod.Dockerfile
      no_cache: true
    # Set environment variables based on the .env file
    env_file:
      - .env.nextjs
    volumes:
      # - ./volumes/eoffice:/app
      - ./volumes/eoffice/src:/app/src
      - ./volumes/eoffice/public:/app/public
      - ./.env.nextjs:/app/.env
      # - ./volumes/eoffice/components.json:/app/components.json
      # - ./volumes/eoffice/next.config.mjs:/app/next.config.mjs
      # - ./volumes/eoffice/tsconfig.json:/app/tsconfig.json
      # - ./volumes/eoffice/tailwind.config.ts:/app/tailwind.config.ts
      # - ./volumes/eoffice/postcss.config.mjs:/app/postcss.config.mjs
      - ./volumes/uploads/nextjs:/uploads
    environment:
      NODE_ENV: production 
      WAIT_HOSTS: mysql:3306
    restart: always
    # ports:
    #  - 3000:3000
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:80"
      - "8001:81"
      - "3000:3000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/poc-mini-fileserver:/var/www/poc-mini-fileserver
      - ./volumes/legacy-edispo:/var/www/legacy-edispo
      - ./volumes/uploads:/var/www/uploads
      - ./volumes/logs/log.txt:/var/www/logs/log.txt

    depends_on:
      - php-fpm
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
