# Stage 1: Build
FROM node:20 as build

# Install pnpm
RUN npm install -g pnpm

# Create and change to the app directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Generate Prisma Client
RUN pnpm prisma generate --schema ./prisma/db-edispo/schema.prisma
RUN pnpm prisma generate --schema ./prisma/db-penomoran/schema.prisma

# Build the project
RUN pnpm build

# Stage 2: Production
FROM node:20 as production

# Install qpdf
RUN apt-get update && apt-get install -y qpdf && apt-get clean

# Create and change to the app directory
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy the built project from the build stage
COPY --from=build /app /app

# Install only production dependencies
RUN pnpm install --prod

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["pnpm", "start"]
