version: '3.1'

services:
  mysql:
    image: mariadb:10.4.18  # Updated to MariaDB 10.4.18
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/backups:/backups
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
      
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./volumes/poc-mini-fileserver:/var/www/poc-mini-fileserver
      - ./volumes/logs/poc-mini-fileserver.log:/var/www/log/log.txt
      - ./volumes/legacy-edispo:/var/www/legacy-edispo
      - ./.env.fileserver:/var/www/poc-mini-fileserver/.env
      - ./volumes/uploads/poc-mini-fileserver:/var/www/uploads

    networks:
      - app-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    # volumes:
      # - ./volumes/eoffice-perwakilan:/app
      # - ./.env.nextjs:/app/.env
      # - ./volumes/uploads/eoffice-perwakilan:/uploads
    networks:
      - app-network
  

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:80"
      - "8001:81"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/poc-mini-fileserver:/var/www/poc-mini-fileserver
      - ./volumes/legacy-edispo:/var/www/legacy-edispo
      - ./volumes/uploads:/var/www/uploads
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
