version: '3.1'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./volumes/poc-mini-fileserver:/var/www/html
      - ./volumes/legacy-edispo:/var/www/other
      - ./.env:/var/www/html/.env
      - ./volumes/uploads:/var/www/html/uploads
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:80"
      - "8001:81"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/poc-mini-fileserver:/var/www/html
      - ./volumes/legacy-edispo:/var/www/other
      - ./volumes/uploads:/var/www/html/uploads
    depends_on:
      - php-fpm
    networks:
      - app-network

  mysql:
    image: mariadb:10.4.18  # Updated to MariaDB 10.4.18
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/backups:/backups
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: